apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: ingress-basic
  name: sohel-eastus-cloudapp-azure-com-cert-staging
spec:
  secretName: sohel-eastus-cloudapp-azure-com-staging
  dnsNames:
  - sohel.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - sohel.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  